spring:
  application:
    name: nacos-discovery-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        username: nacos
        password: nacos
server:
  port: 8071
#  servlet:
#    context-path: /provider